# Generated by Django 4.1.3 on 2022-11-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervencioneje',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='intervencionvehiculo',
            name='pm',
        ),
        migrations.CreateModel(
            name='RegistroIntervencionSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.consistenciasi')),
                ('interv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.intervencionvehiculo')),
            ],
        ),
    ]
