# Generated by Django 4.1.3 on 2022-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_intervencioneje_pm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mensaje', models.CharField(blank=True, max_length=250, null=True)),
                ('foto', models.CharField(blank=True, max_length=16, null=True)),
                ('subproyecto', models.CharField(choices=[('Ejes', 'Ejes'), ('Cambiador', 'Cambiador'), ('Vagones', 'Vagones'), ('Banco Tria', 'Banco Tria'), ('Banco Córdoba', 'Banco Córdoba')], default='Ejes', max_length=15)),
                ('alerta', models.BooleanField(default=False)),
                ('logro', models.BooleanField(default=False)),
            ],
        ),
    ]
