# Generated by Django 4.1.3 on 2022-12-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
