# Generated by Django 4.1.3 on 2022-11-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingenieria', '0001_initial'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('num_conjuntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConjuntoSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('num', models.IntegerField(default=0)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('matricula', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('km_origen', models.FloatField(default=0)),
                ('fecha_origen', models.DateField(default='2022-01-01')),
                ('fecha_fab', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('km_proximo_mant', models.FloatField(blank=True, default=0, null=True)),
                ('nivel_proximo_mant', models.IntegerField(default=0)),
                ('estado_servicio', models.CharField(choices=[('BAJA', 'BAJA'), ('CIRCULANDO', 'CIRCULANDO'), ('PARADO', 'PARADO'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='PARADO', max_length=15)),
                ('observaciones_servicio', models.CharField(default='sin observaciones', max_length=80)),
                ('transmitiendo', models.BooleanField(default=False)),
                ('alarma', models.BooleanField(default=False)),
                ('ultimo_evento_dt', models.DateTimeField(blank=True, null=True)),
                ('en_nudo', models.BooleanField(default=False)),
                ('vel', models.FloatField(blank=True, default=0, null=True)),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('km_totales', models.FloatField(default=0)),
                ('EEM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.eem')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.owner')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='SistIntegradoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('marcado', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('imagen', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('EEM', models.ForeignKey(limit_choices_to={'de_bogies': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.eem')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.owner')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('num', models.IntegerField(default=0)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.conjuntosi')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('num_elementos', models.IntegerField(default=0)),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='conjuntos', to='vehiculos.conjuntoeje')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tipoelementoeje')),
            ],
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('km_origen', models.FloatField(default=0)),
                ('fecha_origen', models.DateField(default='2022-01-01')),
                ('fecha_fab', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('km_proximo_mant', models.FloatField(default=0)),
                ('nivel_proximo_mant', models.IntegerField(default=0)),
                ('estado_servicio', models.CharField(choices=[('BAJA', 'BAJA'), ('CIRCULANDO', 'CIRCULANDO'), ('PARADO', 'PARADO'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='PARADO', max_length=15)),
                ('observaciones_servicio', models.CharField(default='sin observaciones', max_length=80)),
                ('alarma_temp', models.BooleanField(default=False)),
                ('alarma_aceleraciones', models.BooleanField(default=False)),
                ('alarma_cambio', models.BooleanField(default=False, null=True)),
                ('alarma_mantenimiento', models.BooleanField(default=False, null=True)),
                ('tempa', models.FloatField(blank=True, default=25.0, null=True)),
                ('tempb', models.FloatField(blank=True, default=25.0, null=True)),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('num_cambios', models.IntegerField(default=0)),
                ('km_totales', models.FloatField(default=0)),
                ('coef_trabajo', models.FloatField(default=0)),
                ('EEM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.eem')),
                ('fabricante', models.ForeignKey(blank=True, limit_choices_to={'de_ejes': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.owner')),
                ('tipo_eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tipoeje')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ejes', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('marcado', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('imagen', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('EEM', models.ForeignKey(limit_choices_to={'de_bogies': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.eem')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.owner')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vehiculos.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='conjuntosi',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.sistintegradovehiculo'),
        ),
        migrations.AddField(
            model_name='conjuntoeje',
            name='eje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='conjuntos', to='vehiculos.eje'),
        ),
        migrations.AddField(
            model_name='conjuntoeje',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tipoconjuntoeje'),
        ),
        migrations.CreateModel(
            name='ConjuntoDistribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('num', models.IntegerField(default=0)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.distribuidor')),
            ],
        ),
    ]
