# Generated by Django 4.1.3 on 2023-02-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_remove_vehiculo_codigo_alter_vehiculo_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='clase',
            field=models.CharField(choices=[('LOCOMOTORA', 'Locomotora'), ('AUXILIAR', 'Vehículo Auxiliar'), ('VAGON', 'vagón')], default='VAGON', max_length=15),
        ),
    ]
