# Generated by Django 4.1.3 on 2023-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_vehiculo_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='en_circulación',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='en_mantenimiento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='en_servicio',
            field=models.BooleanField(default=True),
        ),
    ]
