# Generated by Django 4.1.3 on 2023-02-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_vehiculo_en_circulación_vehiculo_en_mantenimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='en_circulación',
            new_name='en_circulacion',
        ),
    ]
