# Generated by Django 4.1.3 on 2023-03-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_rename_en_circulación_vehiculo_en_circulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='en_circulacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eje',
            name='en_mantenimiento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eje',
            name='en_servicio',
            field=models.BooleanField(default=True),
        ),
    ]
