# Generated by Django 4.1.3 on 2022-11-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConjuntoEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('descripción', models.CharField(max_length=25, unique=True)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConjuntoSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('descripción', models.CharField(max_length=25, unique=True)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSistemaIntegrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('descripción', models.CharField(max_length=25, unique=True)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionCambiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('anchos', models.CharField(choices=[('UIC-IB', 'UIC(1435) <> IBÉRICO (1668)'), ('UIC-RUS', 'UIC(1435) <> RUSO (1520)'), ('METR-UIC', 'MÉTRICO(1000) <> UIC(1435)')], default='UIC-IB', max_length=12)),
                ('longitud_desencerrojado', models.FloatField(default=6000)),
                ('longitud_cambio_rueda', models.FloatField(default=6000)),
                ('longitud_encerrojado', models.FloatField(default=6000)),
                ('longitud_total', models.FloatField(default=36000)),
                ('fecha_aprovacion', models.DateField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.aprovador')),
                ('certificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.certificador')),
                ('diseñador', models.ForeignKey(limit_choices_to={'de_cambiadores': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.diseñador')),
                ('fabricante', models.ForeignKey(blank=True, limit_choices_to={'de_cambiadores': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('descripción', models.CharField(max_length=25, unique=True)),
                ('tipo_uic', models.CharField(max_length=16)),
                ('serie_uic', models.CharField(max_length=16)),
                ('num_bogies', models.IntegerField(blank=True, default=0, null=True)),
                ('imagen', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('plan_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mantenimiento.planmantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoElementoSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('descripción', models.CharField(max_length=25, unique=True)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('tipo_conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipoconjuntosi')),
            ],
        ),
        migrations.CreateModel(
            name='TipoElementoEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('descripción', models.CharField(max_length=25, unique=True)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('tipo_conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipoconjuntoeje')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('anchos', models.CharField(choices=[('UIC-IB', 'UIC(1435) <> IBÉRICO (1668)'), ('UIC-RUS', 'UIC(1435) <> RUSO (1520)'), ('UIC-RUS-IB', 'UIC <> RUSO <> IBÉRICO'), ('METR-UIC', 'MÉTRICO(1000) <> UIC(1435)'), ('UIC', 'UIC (1435)'), ('IB', 'IB (1668)')], default='UIC-IB', max_length=12)),
                ('fecha_aprovacion', models.DateField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField(blank=True, null=True)),
                ('documentacion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('imagen', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.aprovador')),
                ('certificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.certificador')),
                ('diseñador', models.ForeignKey(limit_choices_to={'de_ejes': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.diseñador')),
                ('plan_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mantenimiento.planmantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='tipoconjuntosi',
            name='tipo_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tiposistemaintegrado'),
        ),
        migrations.AddField(
            model_name='tipoconjuntoeje',
            name='tipo_eje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipoeje'),
        ),
        migrations.CreateModel(
            name='SistemasVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tiposistemaintegrado')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='EjesVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipoeje')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ConsistenciaSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('nivel_entrada', models.IntegerField(default=1)),
                ('descripción', models.CharField(max_length=125, unique=True)),
                ('valor_min', models.FloatField(blank=True, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('instruccion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('tipo_conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipoconjuntosi')),
            ],
        ),
        migrations.CreateModel(
            name='ConsistenciaEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('nivel_entrada', models.IntegerField(default=1)),
                ('descripción', models.CharField(max_length=125, unique=True)),
                ('valor_min', models.FloatField(blank=True, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('instruccion_tecnica', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('tipo_conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipoconjuntoeje')),
            ],
        ),
    ]
