# Generated by Django 4.1.3 on 2022-12-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0004_consistenciaeje_unidades_medida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovehiculo',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
