# Generated by Django 4.1.3 on 2022-11-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=25, null=True)),
                ('material', models.CharField(blank=True, max_length=25, null=True)),
                ('normativa', models.CharField(blank=True, max_length=15, null=True)),
                ('revision', models.IntegerField(default=0)),
                ('fecha_revisión', models.DateField(blank=True, null=True)),
                ('elaborado_por', models.CharField(blank=True, max_length=15, null=True)),
                ('revisado_por', models.CharField(blank=True, max_length=15, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('dias_siguiente_nivel', models.IntegerField(default=1000)),
                ('km_siguiente_nivel', models.FloatField(default=100000)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.planmantenimiento')),
            ],
        ),
    ]
